title: eiguike
email: rick.eihara@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  i'm not sure what to insert here, let it be.
baseurl: ""
url: "http://eiguike.github.io"
twitter_username: eiguike
github_username: eiguike

theme: minima
plugins:
  - jekyll-feed
